version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - backend/.env
    environment:
      - POSTGRES_HOST=postgres_pinger
    ports:
      - "${REST_SERVER_PORT}:${REST_SERVER_PORT}"
    depends_on:
      postgres_pinger:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:${REST_SERVER_PORT}/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - ping_network

  pinger:
    build:
      context: ./pinger
      dockerfile: Dockerfile
    container_name: pinger
    env_file:
      - .env
    environment:
      - HOST=backend
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ping_network

  frontend:
    build:
      context: ./front
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-I", "http://localhost:3000" ]
      interval: 15s
      timeout: 10s
      retries: 5
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - ping_network

  postgres_pinger:
    image: postgres:15-alpine
    container_name: postgres_container_pinger
    env_file:
      - backend/.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres_pinger
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: [ "CMD-SHELL", "psql -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 15s
      timeout: 10s
      retries: 5
    networks:
      - ping_network

volumes:
  postgres_data:

networks:
  ping_network:
    driver: bridge
